# Vaadin 24.8 configuration file
vaadin.launch-browser=true
vaadin.productionMode=false

# Server configuration
spring.application.name=Pangreksa Web

# Database configuration
spring.datasource.url=jdbc:postgresql://128.199.166.158:5432/pangreksadb
spring.datasource.username=pangreksa_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool settings
spring.datasource.hikari.maximum-pool-size=200


