# Vaadin 24.8 configuration file
vaadin.launch-browser=true
vaadin.productionMode=false

# Application configuration
logging.level.org.atmosphere=warn
packages=com.vaadin,org.vaadin,com.flowingcode,con.fusi24.pangreksa

# Server configuration
spring.application.name=Pangreksa Web

# Database configuration
spring.datasource.url=jdbc:postgresql://128.199.166.158:5432/pangreksadb
spring.datasource.username=hris_user
spring.datasource.password=iqbalchandra
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool settings
spring.datasource.hikari.maximum-pool-size=200


